### PR TITLE
Validate multiple choice question parts

### PR DESCRIPTION
**Pull request by Bluesy1**
I've multiple times been tripped up by small errors that cause esoteric and sometimes hard to diagnose issues on PrarieLearn (most recently, in open-resources/instructor_stats_bank#517).

This adds in a function that emulates the validation done by PrairieLearn to raise an error when the question is built that points out the exact part which is invalid.

### CODE REVIEW

**Comment by Bluesy1** [comment]
For reference, this is the sort of console log returned by PrairieLearn that is difficult to diagnose, especially if there are multiple MCQ parts in a question:
```py
Traceback (most recent call last):
  File "/PrairieLearn/apps/prairielearn/python/zygote.py", line 395, in <module>
    worker_loop()
  File "/PrairieLearn/apps/prairielearn/python/zygote.py", line 303, in worker_loop
    val = method(*args)
  File "/PrairieLearn/apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.py", line 426, in prepare
    answers_to_display = prepare_answers_to_display(
  File "/PrairieLearn/apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.py", line 223, in prepare_answers_to_display
    raise ValueError(
ValueError: pl-multiple-choice element must have at least 1 correct answer, or add none-of-the-above set to "correct" or "random"
Traceback (most recent call last):
  File "/PrairieLearn/apps/prairielearn/python/zygote.py", line 437, in <module>
    raise Exception(
Exception: worker process exited unexpectedly with status 256
```
This is taken from here: https://ca.prairielearn.com/pl/course_instance/4024/instructor/question/308815/preview?variant_id=16580132

**Comment by firasm** [comment]
ooooh this is great, I've always wanted this feature.

**Comment by firasm** [comment]
I think I know the answer to this, but could you confirm that this change won't break any existing questions that are in the bank?

**Comment by Bluesy1** [comment]
@firasm It should only break questions that are inherently broken already, i.e., generate broken variants.
I locally checked it with the stats and datascience bank and had no errors, so I don't believe it should break any existing questions

**Pull request merged**
