### PR TITLE
Update prairielearn.py to get most up to date version of `sympy_to_json`

### LINKED ISSUE #79: Deal with data frames showing on Myst Substitution
Screenshot 2023-07-25 at 12 51 53 PM

See: https://prairielearn.readthedocs.io/en/latest/elements/#pl-dataframe-element

### PR DESCRIPTION
**Pull request by Bluesy1**
This uses `httpimport` to get the `python_helper_sympy` file from the main PrairieLearn repo

It adds 2 new direct dependencies (only 1 of which is completely new): `httpimport` and `typing-extensions`

`typing-extensions` was previously installed indirectly, but was added as a direct dependency so that we know all 3rd party modules `python_helper_sympy` depends on are installed.

Supersedes #58

Incidentally, this should at least partially fix #79 probably

### CODE REVIEW

**Review by firasm — COMMENTED** [review]
this looks good on the surface...good solution!

**Comment by Bluesy1** [comment]
It looks like the tests are failing due to the updates to Problem Bank Helpers
Should I fix that here or in a separate PR?

**Comment by firasm** [comment]
Yea that’s what I’m trying to decide right now.

**Comment by firasm** [comment]
I think this PR is pretty big as it is, can you quickly confirm if it’s only pbh updates that are causing this to fail?

if so, we can merge this, and then update the test files.

**Comment by Bluesy1** [comment]
The first time the tests failed was commit 77ed72d513bdede56b76a6f3751bf8caacd6e45e, where PBH was updated

Also, the only changes that the tests are complaining about is this, 8 times
image

**Comment by Bluesy1** [comment]
#82 contains the changes to fix the tests, it was easy enough to create a separate PR to fix it since the failures aren't caused from here

**Pull request merged**
