### PR TITLE
Setup Trusted Publishing Workflow and Simplify Release Process

### PR DESCRIPTION
**Pull request by Bluesy1**
This an experiment, I'm not sure if there's appetite for this, if there's not for any or all of this, that's not a problem, it didn't take me that long to put this together.

This does a few correlated things, one which should hopefully make publishing new version of PBS easier and allow a limited number of trusted people to do without giving them access to project settings on pypi.

The first thing it does helps check that PBS works properly after being built - it tests that the tests still pass when run against a built artifact.

The second thing it does, is that it tests that changes don't break the problem banks.

The third thing only happens when a new release is created in GitHub. It will require a few things to be setup on PyPI/the repository settings (as of writing I cannot do either of these steps).

The first is to add a new environment called "publish" to the repository under settings > environments. 
I would recommend the following protection rules be applied:
1. Required Reviewers - set this to be only the people and/or teams who should be able to publish a new release to PyPI.
2. Under "Deployment branches and tags", make it so only the `main` branch can deploy to the environment.
3. Potentially disable "Allow administrators to bypass configured protection rules"?

<details><summary>Example setup from an unrelated repo I owned I put together to show the UI</summary>

N.B.: I would expect that the allowed people would be different, but I could only add myself on the repo I used to create the screenshot.

image

</details> 

The second thing that needs to be setup to allow this action to fully work is on PyPI. The PyPI docs list the instructions here: https://docs.pypi.org/trusted-publishers/adding-a-publisher/, and the settings should be as follows:
```yaml
Owner: open-resources
Repository name: problem_bank_scripts
Workflow name: publish.yml
Environment name: publish
```

I'm happy to answer any questions about how this works or if there are any concerns that need to be addressed.

### CODE REVIEW

**Comment by Bluesy1** [comment]
@firasm While testing this PR, I found a bug in the code from #95, which I fixed in 01a6294, I can cherry-pick that to its own PR if you'd like.

However, after I fixed that, I noticed #95 breaks the DataSci Bank still is broken with the validation I added (apparently I did my local testing using the wrong script so it didn't pick up all the files): https://github.com/open-resources/problem_bank_scripts/actions/runs/9121359387/job/25080410745?pr=98#step:7:32

The issue here comes from the fact that it is using a float as a truthy value. I see three options here:
1. Change the validation to allow basic python types float/int/str to be used in a boolean context,
2. Go through and fix any error(s) in the datasci bank, or
3. Revert the validation, at least for now, and maybe go through and fix the validation at a later date.

Thoughts?

**Comment by Bluesy1** [comment]
Here's the full diff of what we'd need to do to the datasci bank to make it pass:
```diff
diff --git a/source/000.unsorted/markdown/heading/heading.md b/source/000.unsorted/markdown/heading/heading.md
index 42e2882..f20785d 100644
--- a/source/000.unsorted/markdown/heading/heading.md
+++ b/source/000.unsorted/markdown/heading/heading.md
@@ -34,7 +34,7 @@ server:
 
         data2["params"]["vars"]["title"] = 'Markdown Headings'
 
-        is_big = random.randint(0,1)
+        is_big = random.choice([True, False])
         feedback1 = "The largest font size available in a heading for a markdown document is `H1`, or `#`."
         feedback2 = "`H6`, or `######` is the smallest font size available in a heading for a markdown document."
 
```
I think thats probably an easier change to make than removing the ``validate_multiple_choice`` function or updating it.

Let me know what you think though

**Comment by firasm** [comment]
Hi @Bluesy1  thanks for doing this! I've added GitHub and this repo as a trusted publisher on PyPi

Screenshot 2024-05-19 at 11 17 16 AM

A few things left, here are my notes on what I do before I publish:

```
poetry run pytest

poetry version patch

pico src/problem_bank_scripts/__init__.py

pico tests/test_problem_bank_scripts.py (to update the number)

cd docs; poetry run make html; cd ..

git add .; git commit -m "increment version"; git push

poetry build

poetry publish
```

The most annoying part of this is the manual changing of the version numbers in the `__init__.py` file, could we automate that also? There is actually a test that runs to verify that number is updated correctly in all the different places.

**Comment by Bluesy1** [comment]
@firasm done (kinda)!
I haven't created an action to do it since thats a bit more complicated to do, but there's a bash script to do it which you'd run like follows (terminal output based off of testing on this branch):
```bash
$ bash bump.sh
Usage: bump.sh <VERSION_LEVEL>
  VERSION_LEVEL: The level of the version to bump. One of: patch, minor, major
$ bash bump.sh patch
Bumping version from 0.10.1 to 0.10.2
Bumping version from 0.10.1 to 0.10.2 in __init__.py
Bumping version from 0.10.1 to 0.10.2 in tests/test_problem_bank_scripts.py
[publish-via-action 7dece7f] Increment version from 0.10.1 to 0.10.2
 4 files changed, 4 insertions(+), 4 deletions(-)
$ git push --tags
```

**Comment by Bluesy1** [comment]
Updated the Readme to have proper installation instructions.

I'm going to go ahead and merge this in an hour or two if there are no objections and start the process for a new release so we can get the attribution out to everyone to make there be less migration work for the stats library. We can modify/cleanup the release process in a follow-up if we find there are issues with it.

**Pull request merged**
