### PR TITLE
Update codeblock answer substitution

### LINKED ISSUE #68: Support bacticks when answer options are created from a list, and other answer types
- Currently if someone creates a list of answer options and uses a for loop to generate the data dict, we don't convert backticks to codeblocks, which can be seen here: https://github.com/open-resources/instructor_datascience_bank/pull/168#discussion_r1259804316
- Also, the current solution doesn't support the pl-matching type, which should be able to use codeblocks potentially

### PR DESCRIPTION
**Pull request by Bluesy1**
The changes here happened via cascade, I can split this into 4 separate PRs if wanted.

I recommend viewing the changes commit by commit, to understand what each is for:

- First I changed the codeblock substitution implementation, as per #68 
- Then, while testing this on a `pl-matching` question, I found and fixed an error with distractor answers (cc @amurph24 for https://github.com/open-resources/instructor_datascience_bank/pull/171#discussion_r1259040759)
- Then, testing that change, I noticed our tests weren't checking that `question.html` was being generated correctly, so I fixed that
- Which lead me to an error in my changes in #51 , which is now fixed.

Resolves #68

### CODE REVIEW

**Comment by firasm** [comment]
These three can be handled in the same PR:
- fix to the unicode is fine, though I think we need to update our templates so there's a bit more complicated LaTeX in there so we don't keep missing weird edge cases (but this can be done in a later PR)
- fix to the matching question is also fine
- fix to question.html not being checked is also fine

---

- codeblock substitution is probably what we need to discuss
    - I don't like relying on `pbs` to be installed in courses, I'm actually trying to get to a point where only `pbh` is installed in courses as it's a much simpler dependency. Maybe we can move `pbs.backticks_to_code_tags` to `pbh`? (wherever `pbs is installed, `pbh` will likely exist, but not vice versa)

We should have a meeting about this to hammer out some things as it'll require some back and forth.

**Comment by Bluesy1** [comment]
> * I don't like relying on `pbs` to be installed in courses, I'm actually trying to get to a point where only `pbh` is installed in courses as it's a much simpler dependency. Maybe we can move `pbs.backticks_to_code_tags` to `pbh`? (wherever `pbs is installed, `pbh` will likely exist, but not vice versa)

The alternative I had thought of was to just move the body of the convert function into the injected code, and inject an `re` import instead of a `pbs` import - I just wasn't sure if that would be too messy, injecting those 12 lines of code in. Moving it to `pbh` is a valid alternative.

If you want to have a meeting to discuss the different options, I can be available on Thursday for that.

I'll go ahead and split the changes that aren't for the codeblocks into a different PR so those can be merged in separately since this may take some time to figure out the optimal solution for

**Comment by Bluesy1** [comment]
I've rebased this off of #70 now, such that we can keep the changes in test running for anything made here, to be sure it works properly, but such that clean merging separately should hopefully be possible, though I suppose another rebase may be necessary down the line (should be relatively simple I think though)

**Comment by Bluesy1** [comment]
Change implemented as discussed earlier, this should not be merged (or at least merged and released) until a new release of PBH with open-resources/problem_bank_helpers#17 merged is cut (and ideally the dependency is bumped here, but that doesn't matter as much)

**Pull request merged**
