### PR TITLE
sympy_to_json and to_json functions updated

### PR DESCRIPTION
**Pull request by firasm**

### CODE REVIEW

**Comment by Bluesy1** [comment]
I've updated this to not fail tests, and I've actually commented out the xfail marker from the tests for q07a and q07b, since they seem to be fairly stable, looking at the actions log for the tests for the last while, and they indicated an actual issue here

**Comment by firasm** [comment]
I'm reconsidering separately maintaining the `prairielearn.py` file for just one function - it's a huge burden and prone to being forgotten.

Perhaps a better idea is to use something like [httpimport](https://pypi.org/project/httpimport/) ([from here](https://stackoverflow.com/a/58102363))...

Need to think about it.

- [ ] Also, Ideally I'd like to move this into `problem_bank_helpers` - the `to_json` function is the only reason pbs needs to be installed in every course...

**Comment by Bluesy1** [comment]
I'm still not sure why the file doesn't just exist on prarielearn for us - https://prairielearn.readthedocs.io/en/latest/question/#question-data-storage seems to indicate it should just exist on pl for us to use 
Or is this an issue with that we can't use it that way locally for question dev with the way we convert from md to pl format?
If that's the issue, we could just manually inject that file into sys.modules probably (quite hacky though to be fair)

**Comment by firasm** [comment]
It exists on prairielearn yes, but we also need it in GitHub actions, and when testing questions locally etc.,

Basically wherever server.py is executed.

**Comment by firasm** [comment]
Closing this, as @Bluesy1 will work on a different solution to resolve this using remote imports.

**Pull request closed without merging**
